supabase is set we have this also Unhandled Runtime Error
Error: FormField is not defined

src/app/(auth)/settings/page.tsx (332:20) @ SettingsPage

  330 |               <Form {...form}>
  331 |                 <form onSubmit={form.handleSubmit(onAddStaffSubmit)} className="space-y-6">
> 332 |                   <FormField
      |                    ^
  333 |                     control={form.control}
  334 |                     name="name"
  335 |                     render={({ field }) => (

Call Stack 2
Show 1 ignore-listed frame(s)
SettingsPage
src/app/(auth)/settings/page.tsx (332:20)